### ISSUE TITLE
modifications to DHARMA_CritEdSarvavajrodaya.xml and CritEd schema

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-sanskrit-philology#2]
@ajaniak — thanks for importing this file and its Translation from LaTeX source code. At present, the files are not yet valid and hence cannot be displayed. I will list stuff to be changed in this checklist, to which I will gradually be making additions.

- [x] 1. all cases of `<rdg type="emn" wit="#XYZ">READING</rdg><witDetail wit="#XYZ" type="silently"/>` should become `<rdg wit="#XYZ">READING</rdg><witDetail wit="#XYZ" type="silemn"/>` — **this use of "silemn" is new**
- [x] 2. `<lem type="emn" wit="#([A-Z]+)">(.+)</lem><witDetail wit="#([A-Z]+)" type="silently"/>` should become `<lem wit="#$1">$2</lem><witDetail wit="#$3" type="silemn"/>`.
- [x] 3. I think cases like this `<app><lem type="emn" wit="#MSK">vajradhātvīśvaryā</lem><witDetail wit="#MSK" corresp="#KSP">($\leftarrow$ KSP, Tib.)</witDetail><rdg wit="#cod">vajradhātvīśvaryādi</rdg></app>` can be represented as `<app><lem type="emn" wit="#MSK" evidence="external">vajradhātvīśvaryā</lem><witDetail wit="#MSK" corresp="#KSP #Tib"/><rdg wit="#cod">vajradhātvīśvaryādi</rdg></app>` — **this use of @evidence on `<lem>` and the use of @corresp in `<witDetail>` are new**. Alternative idea: `<app><lem type="emn" wit="#MSK" evidence="external" corresp="#KSP #Tib">vajradhātvīśvaryā</lem><rdg wit="#cod">vajradhātvīśvaryādi</rdg></app>`.
- [x] 4. I think all cases of `<hi rend="italic">$1</hi>` can be replaced by `<foreign xml:lang="san-Latn">$1</foreign>`.
- [x] 5. I have found a few cases where a little chunk of information from the LatEX source seems to have been lost in conversion. See XML line 3334 `<note>incorrectly emends <hi rend="italic">raṅgaṁ rekhāyeta | paraṁ</hi></note>` for last LaTeX-generated pdf "EdT incorrectly emends raṅgaṁrekhāyeta | paraṁ." Can you track down what has gone wrong here?
- [x] 6. All cases like `<app><lem>svahṛdgatavajre</lem><rdg>svahṛdgata[21v1]vajre</rdg></app>` are actually only a way to mark the folio transitions in the codex unicus. If it is possible to isolate all these cases (`<app>`s without attributes on `<lem>` and `<rdg>` and with a sequence [##r/v#] inside `<rdg>`), they can be replaced by regular use of `<pb edRef="#cod" n="$1">` inside the edited text (or a `<lem>`) and where relevant also in a `<rdg>` with `@wit="#cod"`. _Since this point does not lead to file invalidation, it is not a priority._
- [x] 7. When we have a case like this: `<note>STTS 72. 
  The MS and the editions read the first half as follows:
  <rdg wit="#cod #Yed">aho hy anupaman tejaḥ satvadhātvavabhāsanam</rdg>
  <rdg wit="#Hed">aho hy anupamaṁ tejaḥ sattvadhātvavabhāsanam</rdg>
</note>`, do you see any convienent way to represent what is meant other than `<note>STTS 72. 
  The MS and the editions read the first half as follows:
  <ptr target="#cod #Yed">: <foreign xml:lang="san-Latn">aho hy anupaman tejaḥ satvadhātvavabhāsanam</foreign>
  <ptr target="#Hed">: <foreign xml:lang="san-Latn">aho hy anupamaṁ tejaḥ sattvadhātvavabhāsanam</foreign>
</note>`?
- [x] 8. Cases like `<rdg type="emn" wit="#S1">$2</rdg>` should be replaced by `<rdg wit="#$1">$2</rdg><witDetail wit="$1" type="emn"/>` — **this use of @type on `<witDetail>` is new, display should be "$2 $1 (em.)"**
- [x] 9. I now suggest that cases like `<lem wit="$1">$2</lem><witDetail wit="$1" corresp="#$3"/>` can b replaced by `<lem wit="$1">$2</lem><note corresp="$3"/>` — **this use of `<note>` immediately after `<lem>` is new, display should be "$2] em. $1 (∥ $3)"**
- [x] 10. all cases of @wit="" inside `<lem>` can be removed if @wit="#MSK" and @wit="#cod" both appear in `<rdg>`

Of course I would appreciate your advice on the new encoding strategies that I propose. I am not sure @evidence="external" in (2) is necessary as I don't suppose there will be any computational use.

As a next step, I will need your or @michaelnmmeyer's help to make the necessary adjustments to the schema and XLST transformation in order for the usages not yet foreseen in EGC to be validated by the schema and properely displayed.

**Comment by ajaniak** [comment]
@arlogriffiths, 

what about
- [x] ```<lem type="emn" wit="#([A-Z]+)">(.+)</lem><witDetail wit="#([A-Z]+)" type="silently"/>``` would you like to modify it? Should it become ```<lem wit="#$1">$2</lem><witDetail wit="#$3" type="silemn"/>``` or ```<lem type="emn" wit="#$1">$2</lem><witDetail wit="#$3" type="silemn"/>```?

**Comment by arlogriffiths** [comment]
Thanks. My answer is now inserted into the list above.

**Comment by ajaniak** [comment]
For 3. I have handled all the \leftarrow cases except 3 because there were not matching the case you have identify.

For 5. I think the pattern implying a `MSK` was confused in some cases. There are several ways to express it in the file and one of the pattern must have created a conflict deleting the ms sigla, probably also linked with the `<note>`. I have worked to reintroduce most of them, but some might still be missing.

Regarding `@evidence`, the main issue is that this attribute isn't allowed on `<lem>`.  I think `@type` or `<witDetail/>`, even adding a `<note>` seem enough but I might not see what you are trying to achieve adding it.

**Comment by arlogriffiths** [comment]
Thanks for all of that. So let's forget about use of @evidence. I have made a new suggestion in no. 9 above. If that is implemented together with no. 8, I think the file will start to be close to validation.

**Comment by ajaniak** [comment]
For 6. I have changed all the folios, but some are still inside `<note>`.

For 9. Do you mean to say, I should change all `<witDetail/>` for `<note>` (also for `<rdg>` and for `<witDetail type="silemn"/>`?

**Comment by arlogriffiths** [comment]
For 6. thanks. We'll handle the rest manually.

For 9. I can think of: `</rdg><witDetail wit="$1" type="silemn"/>`. This does not  need to be changed, I think.
Please explain which other scenarios you have in mind.

**Comment by arlogriffiths** [comment]
I have added no. 10.

**Comment by ajaniak** [comment]
For 9. I was wondering if it was the `@corresp` requiring the change for `<witDetail/>` to `<note>`. And if yes, should I change those when linked with the `<rdg>`.
Also what about the mix : `<witDetail type="silemn" wit="#MSK" corresp="#KSP #Ied"/>` should it become ` <witDetail type="silemn" wit="#MSK"/><note corresp="#KSP #Ied"/>`. 
All in all, I have just checked in the file with an XPath, it concerns only 39 cases counting both cases.

**Comment by arlogriffiths** [comment]
Now I am home without my computer so a bit more difficult to answer. But yes, I think that use of @corresp was not allowed on witDetail and it also seemed semantically inappropriate to encode corresp on witDetail, so I thought of note. It seems elegant by way of analogy with how we use note in listApp for parallels.

I can only imagine that we have cases of rdg where corresp becomes relevant if MSK made an emn based on a parallel while we overrule the force of that parallel with other arguments. In such cases, yes witDetail with type=emn as well as note with corresp will be required for the rdg.

Yes, that mixed case should be changed as you suggest.

________________________________

**Comment by arlogriffiths** [comment]
Thanks Axelle!
