### ISSUE TITLE
diplEd display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-sanskrit-philology#4]
dear @michaelnmmeyer —

I am not sure why the folder containing html displays at tfd-sanskrit-philology is called docs (https://github.com/erc-dharma/tfd-sanskrit-philology/tree/master/docs). This seems confusing to me as elsewhere we have folders called docs that contain documentation. Can you reorganize the folder structure, paying attention also to where the small number of files delivered by colleagues based in Naples and Pondicherry (@csabakissgit, @FlorindaDS, @dg2018 ) are stored?

Furthermore, my latest commits 4b2cad7181ef2c9186da739b5484e95578e69ecc and e42a96af21d76439a79b78d9ec489ee0c2aa5a92 have not led to the html for the file DHARMA_DiplEdSarvavajrodayaCodex.xml being updated, even though it has no validation problems. Can you push it through?

**Comment by michaelnmmeyer** [comment]
Fixed
